{% set name = "kkcalc" %}
{% set version = "0.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kkcalc-{{ version }}.tar.gz
  sha256: 5c247800953d7152551de64b1e7f61fb3f35945df0100ef80d218354540077be

build:
  number: 0
  entry_points:
    - kkcalc=kkcalc.kk_gui:start_wx
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - wxpython

test:
  imports:
    - kkcalc
    - kkcalc.data
    - kkcalc.kk
    - kkcalc.test_kk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://bitbucket.org/benajamin/kkcalc
  summary: A calculator for the Kramers Kronig transform of X-ray spectra
  license: Unlicense
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mrakitin
